
spring:
    datasource:
        password: letmein
        url: jdbc:mysql://localhost:3306/serverdb
        username: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate: 
            ddl-auto: create 
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true